### PR TITLE
Allow user to build and run app on top of docker containers

### PR DESCRIPTION
**Pull request by mcollovati**
Automatically configures and create tasks of pre integration, integration and post Integration test for each container configured in `dcompose` section.

### CODE REVIEW

**Comment by mcollovati** [comment]
1. pre integration tasks does two things: build and starts a specific container (depending on war task) and expose the local http port as `krail.server.httpPort` system property to the `junitPlatformTestTask`
   post integration tasks stops and removes the container
2. dcompose creates different tasks for each container configured; the integration test task must then depend on specific  container tasks
  So if I want to test on tomcat7 the steps are (more or less) 
  - `buildTomcat7Image`, `createTomcat7Container`, `startTomcat7Container` (pre integration)
  - `stopTomcat7Container`, `removeTomcat7Container` (post integration)
 The integration test task should depend on those tasks so there's a specific task for each container; the integration task itself depends on also on `test` task that the same for all executions

I was not aware of KayTee integration test task (and I see there are also other kinds of test configuration).
My though was to launch separated builds for every environment (so `./gradlew integrationTestTomcat7`, `./gradlew integrationTestTomcat8` etc) but if I correctly understand they should instead run in a single build.

To run all environment tests on a single task maybe we could define a `containerTest` task that depends on each `integrationTest<containerName>` and bind this to the KayTee integrationTest task. Could this work?
Or are there better ways to do it in gradle?

**Comment by davidsowerby** [comment]
It is not surprising you did not know what is in the kaytee plugin - I didn't tell you and there is no documentation.  I apologise for that, I wasn't expecting you to need to know yet.

I think all the parts are there, it is just a case of sticking them together.

I was thinking more of a command line like:

>  ./gradlew test -Ptarget=tomcat7 -Pport=8080

But that doesn't mean it is the only way.

I think a chat might be easiest if possible?  I also need to spend a few minutes looking at dcompose ...

**Comment by davidsowerby** [comment]
I've been thinking about this - your solution may be better than the one I had in my mind.  

Don't make any changes yet I will have more detailed look this morning

**Comment by davidsowerby** [comment]
I get it now, this is a good solution.  Just a couple of points

1. If you could rename the integrationTestTask to avoid naming conflict with kaytee - containerTest would be fine
2. I don't think there is any need to invoke test on all environments - one at a time is sufficient.  If need be, they can be called in sequence from the CLI anyway 

> ./gradlew containerTestTomcat7 containerTestTomcat8

3. Could you make a reference from the wiki to the dcompose wiki, specifically about setting properties
4. There is a possibility that upgrading to Spek 2.0 will break your method of transferring the port number.  There was a discussion in the Spek team about not using the JUnit platform at all for version 2.  I am not sure whether that has happened, but I suggest we raise an issue "Upgrade to Spek 2 when available", and include a comment about how you transfer the port number.

**Comment by mcollovati** [comment]
> Could you make a reference from the wiki to the dcompose wiki, specifically about setting properties

Should be added to `Test Environment` page?

**Comment by davidsowerby** [comment]
> Should be added to Test Environment page?

Yes please

**Comment by davidsowerby** [comment]
should `def integrationTestTask ` be `def containerTestTask`?

**Pull request merged**
